_target_: src.robots.low_cost_robot.low_cost_robot.DualArmLowCostRobot
robot1:
  _target_: src.robots.low_cost_robot.low_cost_robot.LowCostRobot
  shm_name: 
  frame_rate: 30
  device_name: /dev/ttyUSB0
  baudrate: 1_000_000
  servo_ids: [1, 2, 3, 4, 5, 6]
  use_pwm_reader: false
robot2:
  _target_: src.robots.low_cost_robot.low_cost_robot.LowCostRobot
  shm_name: 
  frame_rate: 30
  device_name: /dev/ttyUSB3
  baudrate: 1_000_000
  servo_ids: [1, 2, 3, 4, 5, 6]
  use_pwm_reader: false