# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - paths: default
  - hydra: default
  - extras: default
  - camera: realsense
  - collector: default

tag: camera
tags:
  - ${tag}

# task name, determines output directory path
task_name: "pick_cube"
user_name: "default"
episode_id: 0
